---
apiVersion: v1
kind: Service
metadata:
  name: text-generation-webui # Service名称
  namespace: tgw
  labels:
    app: text-generation-webui    # Service自身标签
spec:
  ports:
  - port: 5000  # K8S集群内部访问Service时使用的端口
    protocol: TCP
    targetPort: 5000  # 目标Pod的监听端口
    name: api
  - port: 5005
    protocol: TCP
    targetPort: 5005
    name: api-stream
  - port: 7860
    protocol: TCP
    targetPort: 7860
    name: web
  selector:
    app: text-generation-webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text-generation-webui
  name: text-generation-webui
  namespace: tgw
spec:
  replicas: 1
  revisionHistoryLimit: 10  # 滚动更新后, 保留的历史版本数
  selector: # 找到匹配的RS
    matchLabels:
      app: text-generation-webui
  strategy: # 更新策略
    rollingUpdate:
      maxSurge: 25% 
      maxUnavailable: 25%
    type: RollingUpdate # 更新类型, 滚动更新
  template:
    metadata:
      labels:
        app: text-generation-webui
    spec:
      tolerations:
        - key: "neuron-load"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
      - image: 928808346782.dkr.ecr.us-west-2.amazonaws.com/text-generation-webui-neuron:latest
        imagePullPolicy: IfNotPresent
        name: text-generation-webui
        resources:
          limits:
            aws.amazon.com/neurondevice: 16
        volumeMounts:
          - name: persistent-storage-for-models
            mountPath: /home/app/text-generation-webui/models
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: persistent-storage-for-models
        persistentVolumeClaim:
          claimName: pvc-efs-tgw